# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_psth', [dirname(__file__)])
        except ImportError:
            import _psth
            return _psth
        if fp is not None:
            try:
                _mod = imp.load_module('_psth', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _psth = swig_import_helper()
    del swig_import_helper
else:
    import _psth
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


SPIKE_FUZZ = _psth.SPIKE_FUZZ
BUF_INIT_SIZE = _psth.BUF_INIT_SIZE
class Spike(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Spike, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Spike, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ts"] = _psth.Spike_ts_set
    __swig_getmethods__["ts"] = _psth.Spike_ts_get
    if _newclass:ts = _swig_property(_psth.Spike_ts_get, _psth.Spike_ts_set)
    __swig_setmethods__["chan"] = _psth.Spike_chan_set
    __swig_getmethods__["chan"] = _psth.Spike_chan_get
    if _newclass:chan = _swig_property(_psth.Spike_chan_get, _psth.Spike_chan_set)
    __swig_setmethods__["unit"] = _psth.Spike_unit_set
    __swig_getmethods__["unit"] = _psth.Spike_unit_get
    if _newclass:unit = _swig_property(_psth.Spike_unit_get, _psth.Spike_unit_set)
    def __init__(self): 
        this = _psth.new_Spike()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _psth.delete_Spike
    __del__ = lambda self : None;
Spike_swigregister = _psth.Spike_swigregister
Spike_swigregister(Spike)

class Channel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Channel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Channel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["chan"] = _psth.Channel_chan_set
    __swig_getmethods__["chan"] = _psth.Channel_chan_get
    if _newclass:chan = _swig_property(_psth.Channel_chan_get, _psth.Channel_chan_set)
    __swig_setmethods__["unit"] = _psth.Channel_unit_set
    __swig_getmethods__["unit"] = _psth.Channel_unit_get
    if _newclass:unit = _swig_property(_psth.Channel_unit_get, _psth.Channel_unit_set)
    def __init__(self): 
        this = _psth.new_Channel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _psth.delete_Channel
    __del__ = lambda self : None;
Channel_swigregister = _psth.Channel_swigregister
Channel_swigregister(Channel)

class SpikeBuf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpikeBuf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpikeBuf, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _psth.SpikeBuf_data_set
    __swig_getmethods__["data"] = _psth.SpikeBuf_data_get
    if _newclass:data = _swig_property(_psth.SpikeBuf_data_get, _psth.SpikeBuf_data_set)
    __swig_setmethods__["size"] = _psth.SpikeBuf_size_set
    __swig_getmethods__["size"] = _psth.SpikeBuf_size_get
    if _newclass:size = _swig_property(_psth.SpikeBuf_size_get, _psth.SpikeBuf_size_set)
    __swig_setmethods__["idx"] = _psth.SpikeBuf_idx_set
    __swig_getmethods__["idx"] = _psth.SpikeBuf_idx_get
    if _newclass:idx = _swig_property(_psth.SpikeBuf_idx_get, _psth.SpikeBuf_idx_set)
    def __init__(self): 
        this = _psth.new_SpikeBuf()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _psth.delete_SpikeBuf
    __del__ = lambda self : None;
SpikeBuf_swigregister = _psth.SpikeBuf_swigregister
SpikeBuf_swigregister(SpikeBuf)

class BinInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BinInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nunits"] = _psth.BinInfo_nunits_set
    __swig_getmethods__["nunits"] = _psth.BinInfo_nunits_get
    if _newclass:nunits = _swig_property(_psth.BinInfo_nunits_get, _psth.BinInfo_nunits_set)
    __swig_setmethods__["binlen"] = _psth.BinInfo_binlen_set
    __swig_getmethods__["binlen"] = _psth.BinInfo_binlen_get
    if _newclass:binlen = _swig_property(_psth.BinInfo_binlen_get, _psth.BinInfo_binlen_set)
    __swig_setmethods__["chanmap"] = _psth.BinInfo_chanmap_set
    __swig_getmethods__["chanmap"] = _psth.BinInfo_chanmap_get
    if _newclass:chanmap = _swig_property(_psth.BinInfo_chanmap_get, _psth.BinInfo_chanmap_set)
    __swig_setmethods__["binfunc"] = _psth.BinInfo_binfunc_set
    __swig_getmethods__["binfunc"] = _psth.BinInfo_binfunc_get
    if _newclass:binfunc = _swig_property(_psth.BinInfo_binfunc_get, _psth.BinInfo_binfunc_set)
    __swig_setmethods__["params"] = _psth.BinInfo_params_set
    __swig_getmethods__["params"] = _psth.BinInfo_params_get
    if _newclass:params = _swig_property(_psth.BinInfo_params_get, _psth.BinInfo_params_set)
    def __init__(self): 
        this = _psth.new_BinInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _psth.delete_BinInfo
    __del__ = lambda self : None;
BinInfo_swigregister = _psth.BinInfo_swigregister
BinInfo_swigregister(BinInfo)

class BinInc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinInc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BinInc, name)
    __repr__ = _swig_repr
    __swig_setmethods__["output"] = _psth.BinInc_output_set
    __swig_getmethods__["output"] = _psth.BinInc_output_get
    if _newclass:output = _swig_property(_psth.BinInc_output_get, _psth.BinInc_output_set)
    __swig_setmethods__["times"] = _psth.BinInc_times_set
    __swig_getmethods__["times"] = _psth.BinInc_times_get
    if _newclass:times = _swig_property(_psth.BinInc_times_get, _psth.BinInc_times_set)
    __swig_setmethods__["tlen"] = _psth.BinInc_tlen_set
    __swig_getmethods__["tlen"] = _psth.BinInc_tlen_get
    if _newclass:tlen = _swig_property(_psth.BinInc_tlen_get, _psth.BinInc_tlen_set)
    __swig_setmethods__["info"] = _psth.BinInc_info_set
    __swig_getmethods__["info"] = _psth.BinInc_info_get
    if _newclass:info = _swig_property(_psth.BinInc_info_get, _psth.BinInc_info_set)
    __swig_setmethods__["spikes"] = _psth.BinInc_spikes_set
    __swig_getmethods__["spikes"] = _psth.BinInc_spikes_get
    if _newclass:spikes = _swig_property(_psth.BinInc_spikes_get, _psth.BinInc_spikes_set)
    __swig_setmethods__["_tidx"] = _psth.BinInc__tidx_set
    __swig_getmethods__["_tidx"] = _psth.BinInc__tidx_get
    if _newclass:_tidx = _swig_property(_psth.BinInc__tidx_get, _psth.BinInc__tidx_set)
    def __init__(self): 
        this = _psth.new_BinInc()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _psth.delete_BinInc
    __del__ = lambda self : None;
BinInc_swigregister = _psth.BinInc_swigregister
BinInc_swigregister(BinInc)


def _hash_chan(*args):
  return _psth._hash_chan(*args)
_hash_chan = _psth._hash_chan

def boxcar(*args):
  return _psth.boxcar(*args)
boxcar = _psth.boxcar

def gaussian(*args):
  return _psth.gaussian(*args)
gaussian = _psth.gaussian

def bin_init(*args):
  return _psth.bin_init(*args)
bin_init = _psth.bin_init

def bin_spikes(*args):
  return _psth.bin_spikes(*args)
bin_spikes = _psth.bin_spikes

def bin_incremental(*args):
  return _psth.bin_incremental(*args)
bin_incremental = _psth.bin_incremental

def bin_inc_spike(*args):
  return _psth.bin_inc_spike(*args)
bin_inc_spike = _psth.bin_inc_spike

def bin_inc_get(*args):
  return _psth.bin_inc_get(*args)
bin_inc_get = _psth.bin_inc_get
# This file is compatible with both classic and new-style classes.


