all:
	python test_riglib_experiment.py
	python test_mixin_features.py
	python test_feature_savehdf.py
	python test_built_in_vfb_task.py
	python test_riglib_bmi.py
	python test_riglib_traits.py
	python test_built_in_vfb_task_mp.py
	python test_mp_proxy.py
	python test_riglib_sink.py
	python test_riglib_source.py

cli:
	python test_riglib_experiment.py
	python test_mixin_features.py
	python test_feature_savehdf.py
	python test_riglib_bmi.py
	python test_riglib_traits.py
	python test_mp_proxy.py
	python test_riglib_sink.py
	python test_riglib_source.py
